replicaCount: 1

image:
  repository: vllm/vllm-openai
  tag: gptoss
  pullPolicy: IfNotPresent

container:
  name: gpt-oss-120b-helm
  args:
    - "--model"
    - "openai/gpt-oss-120b"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8000"
    - "--trust-remote-code"
    - "--tensor-parallel-size"
    - "2"
  env:
    NVIDIA_VISIBLE_DEVICES: "3,4"
    TORCH_CUDA_ARCH_LIST: "9.0"

resources:
  limits:
    nvidia.com/gpu: 2
  requests:
    nvidia.com/gpu: 2
    cpu: "6"
    memory: "64Gi"

volumeMounts:
  - name: dshm
    mountPath: /dev/shm

volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 64Gi   # Increase /dev/shm to 64 GB

service:
  type: NodePort
  port: 8000
  nodePort: 30509
